openapi: "3.0.0"


info:
  title:  E comm TshirtStore
  description: an api for E comm TshirtStore
  version: 1.0.0
  contact:
    email: nazimmazumder68@gmail.com
    url: "https://lco.dev"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for local host -secure
#   - url: "http://localhost:4000/api/v1"
#     description: for local host -regular


servers:
  - url: "{protocol}://localhost:8000/api/{version}"
    description: for local host -secure
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - https
          - http
        default: http

components: 
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth: 
      type: http
      scheme: bearer

paths:
  /dumy:
    get:
      tags:
        - Home         # this will ensure all the requests related to string donot go further down else group together
      summary: returns a greet message from LCO
      responses:
        200:
          description: All good success 
          content: 
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: Server error